INSERT INTO USERACCOUNT (userName, userFullName, emailAddress, password) VALUES ('henman70', 'Henry Chia', 'henry_chia21@hotmail.co.uk', '1234')
INSERT INTO USERACCOUNT (userName, userFullName, emailAddress, password) VALUES ('kinghenry1234', 'Henry Holland', 'kinghenry@hotmail.co.uk', 'password')
INSERT INTO USERACCOUNT (userName, userFullName, emailAddress, password) VALUES ('traveller1234', 'Aylin Firinci', 'travelwithme@hotmail.co.uk', 'hello')
INSERT INTO USERACCOUNT (userName, userFullName, emailAddress, password) VALUES ('king', 'king', 'king@hotmail.co.uk', '1234')


INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Turkey','The Blue Mosque', 'blue-mosque.jpg', 'Built from 1609 to 1616, during the rule of Sultan Ahmed I. It contains a tomb of the founder, a madrasah and a hospice. The Sultan Ahmed Mosque is still popularly used as a mosque.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Turkey','Hagia Sophia Museum', 'hagia-sophia.jpg', 'Hagia Sophia, Turkish Ayasofya, Latin Sancta Sophia, also called Church of the Holy Wisdom or Church of the Divine Wisdom, cathedral built at Constantinople (now Istanbul, Turkey) in the 6th century.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Turkey','Pamukkale', 'pamukkale-img.jpg', 'Pamukkale is a town in western Turkey known for the mineral-rich thermal waters flowing down white travertine terraces on a nearby hillside.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Turkey','15 July Martyrs Bridge', 'july-bridge.jpg', 'The Bosphorus Bridge, known officially as the 15 July Martyrs Bridge and unofficially as the First Bridge, is one of the three suspension bridges spanning the Bosphorus strait in Istanbul, Turkey, thus connecting Europe and Asia.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Turkey','Cappadocia', 'cappadocia-img.jpg', 'Cappadocia (Turkish: Kapadokya) is an area in Central Anatolia in Turkey best known for its unique moon-like landscape, underground cities, cave churches and houses carved in the rocks.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('England','Hagia Sophia Museum', 'hagia-sophia.jpg', 'Hagia Sophia, Turkish Ayasofya, Latin Sancta Sophia, also called Church of the Holy Wisdom or Church of the Divine Wisdom, cathedral built at Constantinople (now Istanbul, Turkey) in the 6th century.')

INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Japan','Mount Fuji', 'mount-fuji.jpg', 'Mt. Fuji is an active volcano about 100 kilometers southwest of Tokyo (also known as Fuji san) it is the tallest peak in Japan, at 3,776 meters.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Japan','Arashiyama', 'arashiyama-img.jpg', 'Arashiyama is a district on the western outskirts of Kyoto, Japan. It also refers to the mountain across the Oi River, which forms a backdrop to the district. ')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Japan','Fushimi Inari Taisha', 'Fushi-img.jpg', 'Fushimi Inari Taisha is the head shrine of the god Inari, located in Fushimi Ward in Kyoto, Japan. The shrine sits at the base of a mountain also named Inari which is 233 metres above sea level. ')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Japan','Osaka', 'osaka-castle.jpg', 'Osaka Castle is a Japanese castle in Chuo-ku, Osaka, Japan. The castle is one of the most famous landmarks in Japan and it played a major role in the unification of Japan during the sixteenth century of the Azuchi-Momoyama period.')
INSERT INTO LOCATION (countryName, locationName, image, description) VALUES ('Japan','Lake Kawaguchi', 'lake-kawaguchi.jpg', 'Lake Kawaguchi is located in the border Fujikawaguchiko and Minobu, southern Yamanashi Prefecture near Mount Fuji, Japan. It is the second largest of the Fuji Five Lakes in terms of surface area.')
